networks:
  mlops-net:
    external: true

services:
  ml-service:
    build: ./ml
    networks:
      - mlops-net

  db:
    build: ./database
    networks:
      - mlops-net

  api-service:
    build: ./api
    networks:
      - mlops-net
    ports:
      - "8000:8000"
    depends_on:
      - ml-service
      - db

  streamlit:
    build: ./streamlit
    networks:
      - mlops-net
    ports:
      - "8501:8501"
    depends_on:
      - api-service
