services:
  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    networks:
      - frontend_net

  api-service:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - ml-service
      - db
    networks:
      - frontend_net
      - backend_net

  ml-service:
    build: ./ml
    expose:
      - "5000"
    networks:
      - backend_net

  db:
    build: ./database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    expose:
      - "5432"
    networks:
      - backend_net

networks:
  frontend_net:
    name: disaster_frontend_net
    driver: bridge
  backend_net:
    name: disaster_backend_net
    driver: bridge
